config/routes.rb
Warekihenkan::Application.routes.draw do
  root 'static_pages#index'

  resources :years, only: [:show]

  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/search', to: 'static_pages#search', via: 'get'

  

end

app/models/year.rb
class Year < ActiveRecord::Base
  validates :christian_era,
    presence: true,
    numericality: { only_integer: true, greater_than: 0 }
  validates :name_of_era, presence: true
  validates :year_of_the_era, 
    presence: true,
    numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @notice ||= nil
    @alert ||= nil
    @years = nil
  end

  def about
  end

  def contact
  end

  def search
    search_word = URI.decode(params[:q])

    unless search_word.empty?
      if search_word.gsub(/\d/,'') == ''
        if search_word.to_i >= 1868 && search_word.to_i <= 2014
          @years = Year.where(christian_era: search_word)
          @notice = '変換が成功しました'
        else
          @alert = '西暦は 1868 〜 2014 の範囲で入力してください'
        end
      else
        @alert = '西暦は半角数字で入力してください'
      end
    end

    render 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "和暦変換"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def my_twitter_path
    "https://twitter.com/succi0303"
  end

  def my_blog_path
    "http://succi.jp/blog/"
  end

  def my_repository_path
    "https://github.com/succi0303/warekihenkan"
  end

  def hatena_bookmark_button_tag
    snippet = <<EOF
<a href="http://b.hatena.ne.jp/entry/http://warekihenkan.herokuapp.com/" class="hatena-bookmark-button" data-hatena-bookmark-title="和暦変換" data-hatena-bookmark-layout="standard-balloon" data-hatena-bookmark-lang="ja" title="このエントリーをはてなブックマークに追加"><img src="http://b.st-hatena.com/images/entry-button/button-only@2x.png" alt="このエントリーをはてなブックマークに追加" width="20" height="20" style="border: none;" /></a><script type="text/javascript" src="http://b.st-hatena.com/js/bookmark_button.js" charset="utf-8" async="async"></script>
EOF
    return snippet.html_safe
  end

  def twitter_button_tag
    snippet = <<EOF
<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://warekihenkan.herokuapp.com/">Tweet</a>
<script src="//platform.twitter.com/widgets.js"></script>
EOF
    return snippet.html_safe
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer id="site-footer">
    <p>
      Copyright &copy; <%= link_to 'prime factor', my_blog_path %>,
      2014 All Rights Reserved
    </p>

    <ul id="social-buttons">
      <li>
        <%= hatena_bookmark_button_tag %>
      </li>
      <li>
        <%= twitter_button_tag %>
      </li>
    </div>
  </footer>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to '和暦変換', root_path, class: 'navbar-brand'  %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Contact', contact_path %></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
  <link href="//netdna.bootstrapcdn.com/bootswatch/3.0.3/flatly/bootstrap.min.css" rel="stylesheet">
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <%= yield %>

  <%= render 'layouts/footer' %>

</body>
</html>

app/views/static_pages/_result.html.erb
<section id="answer-box">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">和暦</h3>
    </div>
    <div class="panel-body">
      <% if @years.nil? %>
        　
      <% else %>
        <%= @years[0].name_of_era %>
        <%= @years[0].year_of_the_era %>
        年
      <% end %>
    </div>
  </div>
</section>

<section id="info-box">
  <% if notice %>
    <div class="alert alert-success"><p id="notice"><%= notice %></p></div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger"><p id="alert"><%= alert %></p></div>
  <% end %>
  <% if notice.nil? && alert.nil? %>
    <div class="alert alert-info">
      <p id="info">西暦を入力して「変換」をクリック</p>
    </div>
  <% end %>
</section>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<div class="container">
  <section class="main">
    <div class="row">
      <aside class="col-md-3">
      </aside>
      <article class="col-md-9">
        <header class="page-header">
          <h1>このサイトについて</h1>
        </header>

        <h3>和暦変換</h3>

        <p>
          このサイトは、明治元年(1868年)から平成25年(2014年)の範囲で、西暦から和暦を調べる単機能のウェブアプリケーションです。
        </p>

        <h3>公開している情報</h3>

        <p>
          このサイトで公開している情報は、主に<a href="http://ja.wikipedia.org/wiki/%E5%85%83%E5%8F%B7%E4%B8%80%E8%A6%A7_%28%E6%97%A5%E6%9C%AC%29">Wikipediaの「元号一覧(日本)」</a>の情報を参考に、サイト作成者が独自に編集したデータを使用しています。
        </p>

        <h3>サイト作成の目的</h3>

        <p>
          このサイトは、<a href="http://rubyonrails.org/">Ruby on Rails</a>によるウェブシステム開発の学習を目的として作成したものです。記載されている情報の正確性は保証いたしませんのでご注意ください。
        </p>
      </article>
    </div>
  </section>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<div class="container">
  <section class="main">
    <div class="row">
      <aside class="col-md-3">
      </aside>
      <article class="col-md-9">
        <header class="page-header">
          <h1>お問い合わせ</h1>
        </header>

        <h3>連絡先</h3>

        <p>
          お問い合わせにつきましては、下記のTwitterアカウント宛てにメッセージをいただくか、ブログのコンタクトフォームよりご連絡をいただくようお願いいたします。
        </p>

        <dl>
          <dt><i class="fa fa-twitter"></i> Twitter</dt>
          <dd><%= link_to '@succi0303', my_twitter_path %></dd>
          <dt><i class="fa fa-rss-square"></i> Blog</dt>
          <dd><%= link_to 'prime factor', my_blog_path %></li></dd>
        </dl>

        <h3>ソースコード</h3>

        <p>
          本ウェブサイトのソースコードはGithubにて公開しています。ご興味を持たれた方は下記のGithubリポジトリをご参照ください。
        </p>

        <dl>
          <dt><i class="fa fa-github"></i> Github</dt>
          <dd><%= link_to 'succi0303/warekihenkan', my_repository_path %></dd>
        </dl>
      </article>
    </div>
  </section>
</div>

app/views/static_pages/index.html.erb
<section class="main" id="top-page">

  <div class="jumbotron">

    <div class="container">
      <i class="fa fa-calendar"></i>
      <h1>和暦変換</h1>
      <p>西暦から和暦を調べる単機能ウェブアプリ</p>
    </div>

  </div>

  <div class="container">

    <section id="query-box">
      <small>1868〜2014の範囲で西暦を入力してください</small>
      <form action="/search" method="get" class="form-inline" role="form">
        <div class="form-group">
          <label for"search-box" class="sr-only control-label">西暦</label>
          <input type="number" name="q" class="form-control"
          placeholder="西暦を入力" id="search-box"
          value="<%= params[:q] %>"autofocus>
        </div>
        <button type="submit" class="btn btn-default">変換</button>
      </form>
    </section>

    <%= render 'result', notice: @notice, alert: @alert, object: @years %>

  </div>

</section>